allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  cloudflared: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@sableclient/sable-call-embedded'

overrides:
  serialize-javascript: '>=7.0.5'
  picomatch: '>=4.0.4'
  smol-toml: '>=1.6.1'
  yaml: '>=2.8.3'

peerDependencyRules:
  allowedVersions:
    'folds>@vanilla-extract/css': '^1.20.1'
    'folds>@vanilla-extract/recipes': '^0.5.7'
    'folds>classnames': '^2.5.1'
    'folds>react': '^18.3.1'
    'folds>react-dom': '^18.3.1'
    'vite-plugin-pwa>vite': '^8.0.3'
